title: 'Nikita Rusetskii blog'
description: 'Nikita Rusetskii blog'
author: 'Nikita Rusetskii'

baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

pagination:
  enabled: true
  debug: true
  per_page: 5
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

plugins:             [jekyll-paginate-v2]

markdown:            kramdown
highlighter:         rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed
